#!/bin/bash
# Created this based on https://docs.travis-ci.com/user/docker/
Rscript -e 'pkgdown::deploy_site_github(ssh_id = Sys.getenv("TRAVIS_DEPLOY_KEY", ""))';
docker build --quiet -t nathanskene/ewce . ;
docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
docker push nathanskene/ewce;
